services:
        adp.listener.controller:
            class: ADP\WechatBundle\EventListener\listenerController
            arguments: [@router, @service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

        adp.listener.request:
            class: ADP\WechatBundle\EventListener\listenerRequest
            scope: request
            arguments: [@request, @service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
