parameters:
  # wechat config
    wechat_Token: adp_wechat_samesame
    wechat_AppID: wx8fcd3f54960f2682
    wechat_AppSecret: 2fd531c6bfd43cff8615884602a33fb6

  # session
    session_login: username
