adp_wechat_homepage:
    path:     /hello/{name}
    defaults: { _controller: ADPWechatBundle:Default:index }

adp_wechat_wechat:
    path:     /wechat/
    defaults: { _controller: ADPWechatBundle:Default:wechat }

adp_wechat_wechattest:
    path:     /wechattest/
    defaults: { _controller: ADPWechatBundle:Default:wechattest }

adp_wechat_api:
    path:     /api/
    defaults: { _controller: ADPWechatBundle:Default:api }

adp_wechat_myjob:
    path:     /myjob/
    defaults: { _controller: ADPWechatBundle:Default:myjob }

adp_wechat_article:
    path:     /article/{pageid}
    defaults: { _controller: ADPWechatBundle:Default:article }
# admin
adp_admin_createmenu:
    path:     /adminapi/createmenu/
    defaults: { _controller: ADPWechatBundle:Adminapi:createmenu }

adp_admin_deletebutton:
    path:     /adminapi/deletebutton/
    defaults: { _controller: ADPWechatBundle:Adminapi:deletebutton }

adp_admin_addsubbutton:
    path:     /adminapi/addsubbutton/
    defaults: { _controller: ADPWechatBundle:Adminapi:addsubbutton }

adp_admin_addmbutton:
    path:     /adminapi/addmbutton/
    defaults: { _controller: ADPWechatBundle:Adminapi:addmbutton }

adp_admin_updatebutton:
    path:     /adminapi/updatebutton/
    defaults: { _controller: ADPWechatBundle:Adminapi:updatebutton }

adp_admin_updateevent:
    path:     /adminapi/updateevent/
    defaults: { _controller: ADPWechatBundle:Adminapi:updateevent }

adp_admin_getevent:
    path:     /adminapi/getevent/
    defaults: { _controller: ADPWechatBundle:Adminapi:getevent }

adp_admin_test:
    path:     /adminapi/test/
    defaults: { _controller: ADPWechatBundle:Adminapi:test }

adp_admin_creatadmin:
    path:     /adminapi/creatadmin/
    defaults: { _controller: ADPWechatBundle:Adminapi:creatadmin }

adp_admin_userdel:
    path:     /adminapi/userdel/
    defaults: { _controller: ADPWechatBundle:Adminapi:userdel }

adp_admin_changepwd:
    path:     /adminapi/changepwd/
    defaults: { _controller: ADPWechatBundle:Adminapi:changepwd }

adp_admin_admincpw:
    path:     /adminapi/admincpw/
    defaults: { _controller: ADPWechatBundle:Adminapi:admincpw }

adp_admin_articleadd:
    path:     /adminapi/articleadd/
    defaults: { _controller: ADPWechatBundle:Adminapi:articleadd }

adp_admin_getadmins:
    path:     /adminapi/getadmins/
    defaults: { _controller: ADPWechatBundle:Adminapi:getadmins }

adp_admin_getadminerinfo:
    path:     /adminapi/getadminerinfo/
    defaults: { _controller: ADPWechatBundle:Adminapi:getadminerinfo }

adp_admin_editarticle:
    path:     /adminapi/editarticle/
    defaults: { _controller: ADPWechatBundle:Adminapi:editarticle }

adp_admin_deletearticle:
    path:     /adminapi/deletearticle/
    defaults: { _controller: ADPWechatBundle:Adminapi:deletearticle }

adp_admin_uploadimage:
    path:     /adminapi/uploadimage/
    defaults: { _controller: ADPWechatBundle:Adminapi:uploadimage }

adp_admin_getmenus:
    path:     /adminapi/getmenus/
    defaults: { _controller: ADPWechatBundle:Adminapi:getmenus }

adp_admin_getmmenu:
    path:     /adminapi/getmmenu/
    defaults: { _controller: ADPWechatBundle:Adminapi:getmmenu }

adp_admin_getbuttoninfo:
    path:     /adminapi/getbuttoninfo/
    defaults: { _controller: ADPWechatBundle:Adminapi:getbuttoninfo }

adp_admin_keywordadd:
    path:     /adminapi/keywordadd/
    defaults: { _controller: ADPWechatBundle:Adminapi:keywordadd }

adp_admin_getkeywordlist:
    path:     /adminapi/getkeywordlist/
    defaults: { _controller: ADPWechatBundle:Adminapi:getkeywordlist }

adp_admin_keyworddel:
    path:     /adminapi/keyworddel/
    defaults: { _controller: ADPWechatBundle:Adminapi:keyworddel }

adp_admin_getkeywordinfo:
    path:     /adminapi/getkeywordinfo/
    defaults: { _controller: ADPWechatBundle:Adminapi:getkeywordinfo }

adp_admin_keywordupdate:
    path:     /adminapi/keywordupdate/
    defaults: { _controller: ADPWechatBundle:Adminapi:keywordupdate }

adp_admin_autoreply:
    path:     /adminapi/autoreply/
    defaults: { _controller: ADPWechatBundle:Adminapi:autoreply }

adp_admin_autoreplyinfo:
    path:     /adminapi/autoreplyinfo/
    defaults: { _controller: ADPWechatBundle:Adminapi:autoreplyinfo }

adp_admin_autoreplydel:
    path:     /adminapi/autoreplydel/
    defaults: { _controller: ADPWechatBundle:Adminapi:autoreplydel }

# outapi
adp_out_myjob:
    path:     /outapi/myjob/
    defaults: { _controller: ADPWechatBundle:Outapi:myjob }

adp_out_logout:
    path:     /outapi/logout/
    defaults: { _controller: ADPWechatBundle:Outapi:logout }

adp_out_login:
    path:     /outapi/login/
    defaults: { _controller: ADPWechatBundle:Outapi:login }

adp_out_ckeditoruploadimage:
    path:     /outapi/ckeditoruploadimage/
    defaults: { _controller: ADPWechatBundle:Outapi:ckeditoruploadimage }

adp_out_articlelist:
    path:     /outapi/articlelist/
    defaults: { _controller: ADPWechatBundle:Outapi:articlelist }

adp_out_getarticle:
    path:     /outapi/getarticle/
    defaults: { _controller: ADPWechatBundle:Outapi:getarticle }

adp_out_soap:
    path:     /outapi/soap/
    defaults: { _controller: ADPWechatBundle:Outapi:soap }

adp_out_pushdata:
    path:     /outapi/pushdata/
    defaults: { _controller: ADPWechatBundle:Outapi:pushdata }

adp_out_popdata:
    path:     /outapi/popdata/
    defaults: { _controller: ADPWechatBundle:Outapi:popdata }

adp_out_testbutton:
    path:     /outapi/testbutton/
    defaults: { _controller: ADPWechatBundle:Outapi:popdata }
# system
adp_manage_index:
    path:     /manage/
    defaults: { _controller: ADPWechatBundle:Manage:index }

adp_manage_menu:
    path:     /manage/menu/
    defaults: { _controller: ADPWechatBundle:Manage:menu }

adp_manage_keyword:
    path:     /manage/keyword/
    defaults: { _controller: ADPWechatBundle:Manage:keyword }

adp_manage_pag:
    path:     /manage/page/
    defaults: { _controller: ADPWechatBundle:Manage:page }

adp_manage_replay:
    path:     /manage/reply/
    defaults: { _controller: ADPWechatBundle:Manage:reply }

adp_manage_preference:
    path:     /manage/preference/
    defaults: { _controller: ADPWechatBundle:Manage:preference }
