services:
  #  adp_wechat.example:
  #      class: ADP\WechatBundle\Example
  #      arguments: [@service_id, "plain_value", %parameter%]

        vendor.MysqliDb:
          class: MysqliDb
          arguments: [%database_host%, %database_user%, %database_password%, %database_name%]

        my.dataSql:
          class: ADP\WechatBundle\Modals\Database\dataSql
          arguments: [@service_container]

        my.Wechat:
          class: ADP\WechatBundle\Modals\Apis\Wechat
          arguments: [@service_container]

        php.redis:
          class: Redis
          calls:
            - [connect, [%redis_host%, %redis_port%]]

        my.RedisLogic:
          class: ADP\WechatBundle\Modals\Database\RedisLogic
          arguments: [@service_container]

        my.functions:
          class: ADP\WechatBundle\Modals\Apis\functions
          arguments: [@service_container]
# form list
        form.adminadd:
          class: ADP\WechatBundle\Forms\adminadd
          scope: request
          arguments: [@request, @service_container]

        form.adminlogin:
          class: ADP\WechatBundle\Forms\adminlogin
          scope: request
          arguments: [@request, @service_container]

        form.changepwd:
          class: ADP\WechatBundle\Forms\changepwd
          scope: request
          arguments: [@request, @service_container]

        form.articleedit:
          class: ADP\WechatBundle\Forms\articleedit
          scope: request
          arguments: [@request, @service_container]

        form.articleadd:
          class: ADP\WechatBundle\Forms\articleadd
          scope: request
          arguments: [@request, @service_container]

        form.articledel:
          class: ADP\WechatBundle\Forms\articledel
          scope: request
          arguments: [@request, @service_container]

        form.buttondel:
          class: ADP\WechatBundle\Forms\buttondel
          scope: request
          arguments: [@request, @service_container]

        form.buttonaddsub:
          class: ADP\WechatBundle\Forms\buttonaddsub
          scope: request
          arguments: [@request, @service_container]

        form.buttonaddm:
          class: ADP\WechatBundle\Forms\buttonaddm
          scope: request
          arguments: [@request, @service_container]

        form.buttonupdate:
          class: ADP\WechatBundle\Forms\buttonupdate
          scope: request
          arguments: [@request, @service_container]
