services:
  #  adp_wechat.example:
  #      class: ADP\WechatBundle\Example
  #      arguments: [@service_id, "plain_value", %parameter%]

        vendor.MysqliDb:
          class: MysqliDb
          arguments: [%database_host%, %database_user%, %database_password%, %database_name%]

        my.dataSql:
          class: ADP\WechatBundle\Modals\Database\dataSql
          arguments: [@service_container]

        my.Wechat:
          class: ADP\WechatBundle\Modals\Apis\Wechat
          arguments: [@service_container]

        php.redis:
          class: Redis
          calls:
            - [connect, [%redis_host%, %redis_port%]]

        my.RedisLogic:
          class: ADP\WechatBundle\Modals\Database\RedisLogic
          arguments: [@service_container]
